obj-$(CONFIG_REALTEK_RTL83XX_API)	+= rtk_switch.o \
									rtl8367c_asicdrv.o \
									rtl8367c_asicdrv_phy.o \
									rate.o \
									rtl8367c_asicdrv_lut.o \
									rtl8367c_asicdrv_rma.o \
									rtl8367c_asicdrv_mirror.o \
									rtl8367c_asicdrv_inbwctrl.o \
									rtl8367c_asicdrv_scheduling.o \
									smi.o \
									port.o \
									rtl8367c_asicdrv_port.o \
									rtl8367c_asicdrv_led.o \
									rldp.o \
									rtl8367c_asicdrv_rldp.o \
									acl.o \
									rtl8367c_asicdrv_acl.o \
									cpu.o \
									rtl8367c_asicdrv_cputag.o \
									vlan.o \
									rtl8367c_asicdrv_vlan.o \
									svlan.o \
									rtl8367c_asicdrv_svlan.o \
									dot1x.o \
									rtl8367c_asicdrv_dot1x.o \
									eee.o \
									rtl8367c_asicdrv_eee.o \
									i2c.o \
									rtl8367c_asicdrv_i2c.o \
									igmp.o \
									rtl8367c_asicdrv_igmp.o \
									interrupt.o \
									rtl8367c_asicdrv_interrupt.o \
									l2.o \
									leaky.o \
									led.o \
									mirror.o \
									oam.o \
									rtl8367c_asicdrv_oam.o \
									ptp.o \
									rtl8367c_asicdrv_eav.o \
									qos.o \
									rtl8367c_asicdrv_qos.o \
									rtl8367c_asicdrv_fc.o \
									stat.o \
									rtl8367c_asicdrv_mib.o \
									storm.o \
									rtl8367c_asicdrv_storm.o \
									rtl8367c_asicdrv_meter.o \
									trap.o \
									rtl8367c_asicdrv_unknownMulticast.o \
									trunk.o \
									rtl8367c_asicdrv_trunking.o \
									rtl8367c_asicdrv_hsb.o \
									rtl8367c_asicdrv_misc.o \
									rtl8367c_asicdrv_green.o \
									rtl8367c_asicdrv_portIsolation.o \
									8364NB-VB_Advantech_phy_testmode.o \
									rtl8364nbi_advantech_ssc.o

obj-$(CONFIG_REALTEK_RTL83XX_PHY_DRIVER)	+= rtl83xx.o

ifdef CONFIG_REALTEK_RTL83XX_MDIO
	ccflags-y		+= -DMDC_MDIO_OPERATION
endif

